---
# Create
#   create certificate requests
- hosts: "{{ hosts | default('all')}}"
  connection: local
  gather_facts: no
  roles:
    - role: base/create_ssl_certificate_requests
      tags: create_ssl_certificate_requests
